/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.udec.poo.edwinmendoza.vistas.gui;

import co.edu.udec.poo.edwinmendoza.Principal;
import dominio.Banco;
import dominio.Sucursal;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Edwin
 */
public class VentanaCrudSucursal extends javax.swing.JDialog {

    public Sucursal nueva = new Sucursal();
    public int respuesta = 0;
    /**
     * Creates new form FormularioSucursal
     */
    public VentanaCrudSucursal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        CampoCodigo = new javax.swing.JTextField();
        CampoDireccion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        CampoCodigoPostal = new javax.swing.JTextField();
        texto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CampoInforme = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CampoBanco = new javax.swing.JComboBox<>();
        BotonAgregar = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("_-.:: Ventana Crud Sucursal ::.-_");

        BotonLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/cepillo.png"))); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO SUCURSAL");

        jLabel2.setDisplayedMnemonic(' ');
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/edificios.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Sucursal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Codigo Sucursal");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Direccion");

        CampoNombre.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N

        CampoCodigo.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });
        CampoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoCodigoKeyTyped(evt);
            }
        });

        CampoDireccion.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        CampoCodigoPostal.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        CampoCodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoPostalActionPerformed(evt);
            }
        });

        texto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        texto.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        texto.setText("Codigo Postal");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Informe");

        CampoInforme.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Banco");

        CampoBanco.setModel(new javax.swing.DefaultComboBoxModel<>(Principal.bancoBd.arrayBancos()));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addComponent(jLabel4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel3)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(51, 51, 51)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(texto)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CampoCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CampoInforme, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                        .addComponent(CampoDireccion))))
                            .addGap(22, 22, 22)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(CampoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CampoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto)
                    .addComponent(CampoCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(CampoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BotonAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/medical-report_8506475.png"))); // NOI18N
        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/edit_5953114.png"))); // NOI18N
        BotonEditar.setText("Editar");
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        BotonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/search_5953174.png"))); // NOI18N
        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/delete_5953164.png"))); // NOI18N
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(BotonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(BotonLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonBuscar)
                            .addComponent(BotonEliminar)
                            .addComponent(BotonLimpiar)
                            .addComponent(BotonEditar)
                            .addComponent(BotonAgregar))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        // TODO add your handling code here:
        
        this.respuesta = JOptionPane.showConfirmDialog(this, "¿seguro que desea agregar esta sucursal?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
        String nombre = CampoNombre.getText();
        String direccion = CampoDireccion.getText();
        String codigoSucursal = CampoCodigo.getText();
        String codigoPostal = CampoCodigoPostal.getText();
        String informe = CampoInforme.getText();
        Banco afiliado = (Banco)CampoBanco.getSelectedItem();
        
        
        try {
            int codigo = Integer.valueOf(codigoSucursal);
            nueva.setCodigo(codigoSucursal);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "el codigo no puede tener letras");
            CampoCodigo.requestFocus();
            CampoCodigo.setSelectedTextColor(Color.red);
            CampoCodigo.selectAll();
            return;
        }
        nueva.setCodigoPostal(codigoPostal);
        nueva.setDireccion(direccion);
        nueva.setNombre(nombre);
        nueva.setInforme(informe);
        try {
            nueva.setBancoAfiliado(Principal.bancoBd.buscarBanco(afiliado.getCodigoIdentificador()));
            if (!Principal.sucursalBd.ExisteSucursal(nueva)) {
                JOptionPane.showMessageDialog(this,"se agrego una sucursal a la base de datos"); 
            }
            Principal.sucursalBd.crearSucursal(nueva);
        } catch (Exception ex) {
            
        }
        
        BotonLimpiarActionPerformed(evt);
        }
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        String codigo = CampoCodigo.getText();
        
        if (codigo.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "El codigo se requiere para buscar una Sucursal");
            return;
        }else {
            try {
                
                nueva = Principal.sucursalBd.buscarSucursal(codigo);
                if (Principal.sucursalBd.traerSucursal(codigo) == null) {
                    JOptionPane.showMessageDialog(this, "La sucursal que busca no se encuentra");
                    
                }else{
                    CampoCodigo.setText(nueva.getCodigo());
                    CampoNombre.setText(nueva.getNombre());
                    CampoCodigoPostal.setText(nueva.getCodigoPostal());
                    CampoDireccion.setText(nueva.getDireccion());
                    CampoInforme.setText(nueva.getInforme());
                    String titulo = this.getTitle();
                    if (titulo.indexOf("Editar") != -1){
                        CampoNombre.setEditable(true);
                        CampoCodigo.setEditable(false); 
                        CampoDireccion.setEditable(true);
                        CampoCodigoPostal.setEditable(true);
                        CampoInforme.setEditable(true);
                    }
                    }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } 
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        // TODO add your handling code here:
        
        this.respuesta = JOptionPane.showConfirmDialog(this, "¿seguro que desea realizar estos cambios?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
        String nombre = CampoNombre.getText();
        String direccion = CampoDireccion.getText();
        String codigoSucursal = CampoCodigo.getText();
        String codigoPostal = CampoCodigoPostal.getText();
        String informe = CampoInforme.getText();
        Banco afiliado = (Banco)CampoBanco.getSelectedItem();
       
        this.nueva.setCodigo(codigoSucursal);
        this.nueva.setCodigoPostal(codigoPostal);
        this.nueva.setDireccion(direccion);
        this.nueva.setNombre(nombre);
        this.nueva.setInforme(informe);
        try {
            
            this.nueva.setBancoAfiliado(Principal.bancoBd.buscarBanco(afiliado.getCodigoIdentificador()));
            Principal.sucursalBd.editarSucursal(nueva);
            
            afiliado.agregarSucursal(nueva);
            Principal.bancoBd.editarBanco(afiliado);
            if (Principal.sucursalBd.traerSucursal(codigoSucursal) != null) {
                JOptionPane.showMessageDialog(this,"se edito la sucursal en la base de datos"); 
                BotonLimpiarActionPerformed(evt);
            }
        } catch (Exception ex) {
        }  
        }
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
        this.respuesta = JOptionPane.showConfirmDialog(this, "¿seguro que desea eliminar esta sucursal?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
        String codigo = CampoCodigo.getText();
        int respuesta = JOptionPane.showConfirmDialog(this, "seguro que desea eliminar este banco", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                Principal.sucursalBd.eliminarSucursal(codigo);
                JOptionPane.showMessageDialog(this, "Se a eliminado el objeto de la base de datos");
                BotonLimpiarActionPerformed(evt);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No se puede eliminar un banco que no existe en la base de datos");
            }
        }
        }
        
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        // TODO add your handling code here:
        String titulo = this.getTitle();
                    if (titulo.indexOf("Editar") != -1) {
                        CampoNombre.setEditable(false);
                        CampoCodigo.setEditable(true); 
                        CampoDireccion.setEditable(false);
                        CampoCodigoPostal.setEditable(false);
                        CampoInforme.setEditable(false);
                    }
                    
        //Limpiar campos
        CampoCodigo.setText("");
        CampoNombre.setText("");
        CampoCodigoPostal.setText("");
        CampoDireccion.setText("");
        CampoInforme.setText("");
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void CampoCodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodigoPostalActionPerformed

    private void CampoCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCodigoKeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_CampoCodigoKeyTyped

    public JButton getBotonAgregar() {
        return BotonAgregar;
    }

    public void setBotonAgregar(JButton BotonAgregar) {
        this.BotonAgregar = BotonAgregar;
    }

    public JButton getBotonBuscar() {
        return BotonBuscar;
    }

    public void setBotonBuscar(JButton BotonBuscar) {
        this.BotonBuscar = BotonBuscar;
    }

    public JButton getBotonEditar() {
        return BotonEditar;
    }

    public void setBotonEditar(JButton BotonEditar) {
        this.BotonEditar = BotonEditar;
    }

    public JButton getBotonEliminar() {
        return BotonEliminar;
    }

    public void setBotonEliminar(JButton BotonEliminar) {
        this.BotonEliminar = BotonEliminar;
    }

    public JButton getBotonLimpiar() {
        return BotonLimpiar;
    }

    public void setBotonLimpiar(JButton BotonLimpiar) {
        this.BotonLimpiar = BotonLimpiar;
    }

    public JTextField getCampoCodigo() {
        return CampoCodigo;
    }

    public void setCampoCodigo(JTextField CampoCodigo) {
        this.CampoCodigo = CampoCodigo;
    }

    public JTextField getCampoCodigoPostal() {
        return CampoCodigoPostal;
    }

    public void setCampoCodigoPostal(JTextField CampoCodigoPostal) {
        this.CampoCodigoPostal = CampoCodigoPostal;
    }

    public JTextField getCampoDireccion() {
        return CampoDireccion;
    }

    public void setCampoDireccion(JTextField CampoDireccion) {
        this.CampoDireccion = CampoDireccion;
    }

    public JTextField getCampoInforme() {
        return CampoInforme;
    }

    public void setCampoInforme(JTextField CampoInforme) {
        this.CampoInforme = CampoInforme;
    }

    public JTextField getCampoNombre() {
        return CampoNombre;
    }

    public void setCampoNombre(JTextField CampoNombre) {
        this.CampoNombre = CampoNombre;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JComboBox<Banco> CampoBanco;
    private javax.swing.JTextField CampoCodigo;
    private javax.swing.JTextField CampoCodigoPostal;
    private javax.swing.JTextField CampoDireccion;
    private javax.swing.JTextField CampoInforme;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
