/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.udec.poo.edwinmendoza.vistas.gui;

import co.edu.udec.poo.edwinmendoza.Principal;
import static co.edu.udec.poo.edwinmendoza.Principal.tipoCuentaBd;
import co.edu.udec.poo.edwinmendoza.metodos.DeCadenaADate;
import co.edu.udec.poo.edwinmendoza.metodos.TipoDeCuentaMetodosController;
import com.toedter.calendar.JDateChooser;
import dominio.Cuenta;
import dominio.Sucursal;
import dominio.TipoDeCuenta;
import java.awt.Color;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Edwin
 */
public class VentanaCrudCuenta extends javax.swing.JDialog {

    
    public Cuenta nueva = new Cuenta();
    public int respuesta = 0;
    /**
     * Creates new form FormularioCuenta
     */
    public VentanaCrudCuenta(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoCuentaSelect = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoSaldoActual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CampoCodigo = new javax.swing.JTextField();
        botonGeneral = new javax.swing.JButton();
        CampoFecha = new com.toedter.calendar.JDateChooser();
        CampoSucursal = new javax.swing.JComboBox<>();
        BotonBuscar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonAgregar = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("_-.:: Ventana Crud Cliente ::.-_");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FORMULARIO CUENTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cuenta"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tipo");

        tipoCuentaSelect.setModel(new javax.swing.DefaultComboBoxModel<>(Principal.tipoCuentaBd.arrayTipoDeCuenta())  );
        tipoCuentaSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCuentaSelectActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha Apertura ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Saldo Actual");

        CampoSaldoActual.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        CampoSaldoActual.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Sucursal");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Codigo Cuenta");

        CampoCodigo.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        CampoCodigo.setToolTipText("");

        botonGeneral.setText("General");
        botonGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGeneralActionPerformed(evt);
            }
        });

        CampoSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(Principal.sucursalBd.arraySucursales()));
        CampoSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoCuentaSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonGeneral)
                            .addComponent(CampoSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipoCuentaSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CampoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CampoSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CampoSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonGeneral)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/search_5953174.png"))); // NOI18N
        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/delete_5953164.png"))); // NOI18N
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/cepillo.png"))); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/medical-report_8506475.png"))); // NOI18N
        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/edit_5953114.png"))); // NOI18N
        BotonEditar.setText("Editar");
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(BotonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(BotonLimpiar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonBuscar)
                            .addComponent(BotonEliminar)
                            .addComponent(BotonLimpiar)
                            .addComponent(BotonEditar)
                            .addComponent(BotonAgregar))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoCuentaSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCuentaSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCuentaSelectActionPerformed

    private void botonGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGeneralActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonGeneralActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        // TODO add your handling code here:
        
        this.respuesta = JOptionPane.showConfirmDialog(this, "seguro que desea agregar este banco", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
        String codigo = CampoCodigo.getText();
        Date fecha = CampoFecha.getDate();
        double saldo = Double.valueOf(CampoSaldoActual.getText());
        TipoDeCuenta tipo = (TipoDeCuenta)tipoCuentaSelect.getSelectedItem();
        Sucursal afiliado = (Sucursal) CampoSucursal.getSelectedItem();
        
        try {
            
            nueva.setCodigoCuentaCliente(codigo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "el codigo no puede tener letras");
            CampoCodigo.requestFocus();
            CampoCodigo.setSelectedTextColor(Color.red);
            CampoCodigo.selectAll();
            return;
        }
        
        nueva.setSaldoMedio(0);
        nueva.setDeposito(0);
        nueva.setSaldoActual(saldo);
        nueva.setFechaApertura(fecha);
        nueva.setCuentaCreada(Principal.sucursalBd.traerSucursal(afiliado.getCodigo()));
        
                try {
                    nueva.setTipoDeCuenta(Principal.tipoCuentaBd.buscarTipoDeCuenta(tipo.getTipo()));
                } catch (Exception ex) {
                    Logger.getLogger(VentanaCrudCuenta.class.getName()).log(Level.SEVERE, null, ex);
                }
        nueva.setClienteDueño(Principal.getClienteSesion());
        try {
            
            if (!Principal.cuentaBd.existeCuenta(nueva)) {
                JOptionPane.showMessageDialog(this,"se agrego una cuenta a la base de datos"); 
            }
            Principal.cuentaBd.crearCuenta(nueva);
            tipo.agregarTipoCuentas(nueva);
            afiliado.agregarCuentas(nueva);
            Principal.sucursalBd.editarSucursal(afiliado);
            Principal.tipoCuentaBd.editarTipoDeCuenta(tipo);
        } catch (Exception ex) {
            
        }
        }
        BotonLimpiarActionPerformed(evt);
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        String codigo = CampoCodigo.getText();
        
        if (codigo.isEmpty() == true) {
            JOptionPane.showMessageDialog(this, "El codigo se requiere para buscar una Sucursal");
            return;
        }else {
            try {
                
                nueva = Principal.cuentaBd.encontrarBanco(codigo);
                if (nueva == null) {
                    JOptionPane.showMessageDialog(this, "La cuenta que busca no se encuentra");
                    
                }else{
                    CampoCodigo.setText(nueva.getCodigoCuentaCliente());
                    CampoFecha.setDate(nueva.getFechaApertura());
                    CampoSaldoActual.setText(String.valueOf(nueva.getSaldoActual()));
                   
                    
                    String titulo = this.getTitle();
                    if (titulo.indexOf("Editar") != -1){
                        
                        CampoCodigo.setEditable(false); 
                        CampoSaldoActual.setEditable(true);
                    }
                    }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        // TODO add your handling code here:
        this.respuesta = JOptionPane.showConfirmDialog(this, "seguro que desea agregar este banco", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            String codigo = CampoCodigo.getText();
        Date fecha = CampoFecha.getDate();
        double saldo = Double.valueOf(CampoSaldoActual.getText());
        TipoDeCuenta tipo = (TipoDeCuenta)tipoCuentaSelect.getSelectedItem();
        Sucursal afiliado = (Sucursal) CampoSucursal.getSelectedItem();
        
        
        try {
            if (fecha == null) {
                JOptionPane.showMessageDialog(this, "Es obligatorio ingresar la fecha");
                return;
            }
            nueva.setCodigoCuentaCliente(codigo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ingrese los datos de manera correcta");
            return;
        }
        nueva.setSaldoMedio(0);
        nueva.setDeposito(0);
        nueva.setSaldoActual(saldo);
        nueva.setFechaApertura(fecha);
        nueva.setCuentaCreada(Principal.sucursalBd.traerSucursal(afiliado.getCodigo()));
        
                try {
                    nueva.setTipoDeCuenta(Principal.tipoCuentaBd.buscarTipoDeCuenta(tipo.getTipo()));
                } catch (Exception ex) {
                    Logger.getLogger(VentanaCrudCuenta.class.getName()).log(Level.SEVERE, null, ex);
                }
        nueva.setClienteDueño(Principal.getClienteSesion());
        try {
            
            if (!Principal.cuentaBd.existeCuenta(nueva)) {
                JOptionPane.showMessageDialog(this,"se agrego una cuenta a la base de datos"); 
            }
            Principal.cuentaBd.editarCuenta(nueva);
            tipo.agregarTipoCuentas(nueva);
            afiliado.agregarCuentas(nueva);
            Principal.sucursalBd.editarSucursal(afiliado);
            Principal.tipoCuentaBd.editarTipoDeCuenta(tipo);
        } catch (Exception ex) {
            
        }
            BotonLimpiarActionPerformed(evt);
        }
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
        this.respuesta = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea eliminar este empleado?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            String codigo = CampoCodigo.getText();
            try {
                Principal.cuentaBd.eliminarCuenta(codigo);
            JOptionPane.showMessageDialog(this, "Se a eliminado el objeto de la base de datos");
                BotonLimpiarActionPerformed(evt);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "No se puede eliminar una cuenta que no existe en la base de datos");
            }
        }
        
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        // TODO add your handling code here:
        CampoCodigo.setText("");
        CampoSaldoActual.setText("");
        String titulo = this.getTitle();
                    if (titulo.indexOf("Editar") != -1){
                        
                        CampoCodigo.setEditable(true); 
                        CampoSaldoActual.setEditable(false);
                    }
        
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void CampoSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSucursalActionPerformed

    public JButton getBotonAgregar() {
        return BotonAgregar;
    }

    public void setBotonAgregar(JButton BotonAgregar) {
        this.BotonAgregar = BotonAgregar;
    }

    public JButton getBotonBuscar() {
        return BotonBuscar;
    }

    public void setBotonBuscar(JButton BotonBuscar) {
        this.BotonBuscar = BotonBuscar;
    }

    public JButton getBotonEditar() {
        return BotonEditar;
    }

    public void setBotonEditar(JButton BotonEditar) {
        this.BotonEditar = BotonEditar;
    }

    public JButton getBotonEliminar() {
        return BotonEliminar;
    }

    public void setBotonEliminar(JButton BotonEliminar) {
        this.BotonEliminar = BotonEliminar;
    }

    public JButton getBotonLimpiar() {
        return BotonLimpiar;
    }

    public void setBotonLimpiar(JButton BotonLimpiar) {
        this.BotonLimpiar = BotonLimpiar;
    }

    public JDateChooser getCampoFecha() {
        return CampoFecha;
    }

    public void setCampoFecha(JDateChooser CampoFecha) {
        this.CampoFecha = CampoFecha;
    }

    public JTextField getCampoSaldoActual() {
        return CampoSaldoActual;
    }

    public void setCampoSaldoActual(JTextField CampoSaldoActual) {
        this.CampoSaldoActual = CampoSaldoActual;
    }

    public JTextField getCampoCodigo() {
        return CampoCodigo;
    }

    public void setCampoCodigo(JTextField CampoCodigo) {
        this.CampoCodigo = CampoCodigo;
    }

    public JComboBox<Sucursal> getCampoSucursal() {
        return CampoSucursal;
    }

    public void setCampoSucursal(JComboBox<Sucursal> CampoSucursal) {
        this.CampoSucursal = CampoSucursal;
    }

    public JButton getBotonGeneral() {
        return botonGeneral;
    }

    public void setBotonGeneral(JButton botonGeneral) {
        this.botonGeneral = botonGeneral;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JTextField CampoCodigo;
    private com.toedter.calendar.JDateChooser CampoFecha;
    private javax.swing.JTextField CampoSaldoActual;
    private javax.swing.JComboBox<Sucursal> CampoSucursal;
    private javax.swing.JButton botonGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<TipoDeCuenta> tipoCuentaSelect;
    // End of variables declaration//GEN-END:variables

}
