/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.udec.poo.edwinmendoza.vistas.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Edwin
 */
public class VentanaPrincipal extends javax.swing.JFrame {

/**
     * Creates new form VentanaPrincipal
     */
    
   ImagenDeFondo fondo = new ImagenDeFondo();
    
    public VentanaPrincipal() {
        this.setContentPane(fondo);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuBanco = new javax.swing.JMenu();
        itemAgregarBanco = new javax.swing.JMenuItem();
        itemBuscarBanco = new javax.swing.JMenuItem();
        itemEliminarBanco = new javax.swing.JMenuItem();
        itemEditarBanco = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesBanco = new javax.swing.JMenu();
        itemBuscarPorXBanco = new javax.swing.JMenuItem();
        itemBuscarPorYBanco = new javax.swing.JMenuItem();
        MenuSucursal = new javax.swing.JMenu();
        itemAgregarSucursal = new javax.swing.JMenuItem();
        itemBuscarSucursal = new javax.swing.JMenuItem();
        itemEliminarSucursal = new javax.swing.JMenuItem();
        itemEditarSucursal = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuEmpleado = new javax.swing.JMenu();
        itemAgregarEmpleado = new javax.swing.JMenuItem();
        itemBuscarEmpleado = new javax.swing.JMenuItem();
        itemEliminarEmpleado = new javax.swing.JMenuItem();
        itemEditarEmpleado = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesEmpleado = new javax.swing.JMenu();
        itemBuscarPorXEmpleado = new javax.swing.JMenuItem();
        itemBuscarPorYEmpleado = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesSucursal = new javax.swing.JMenu();
        itemBuscarPorXSucursal = new javax.swing.JMenuItem();
        itemBuscarPorYSucursal = new javax.swing.JMenuItem();
        MenuCliente = new javax.swing.JMenu();
        itemAgregarCliente = new javax.swing.JMenuItem();
        itemBuscarCliente = new javax.swing.JMenuItem();
        itemEliminarCliente = new javax.swing.JMenuItem();
        itemEditarCliente = new javax.swing.JMenuItem();
        itemLoginUsuario = new javax.swing.JMenuItem();
        itemRecordarClaveUsuario = new javax.swing.JMenuItem();
        itemCambiarClaveUsuario = new javax.swing.JMenuItem();
        itemSalirUsuario = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesCliente = new javax.swing.JMenu();
        itemBuscarPorXCliente = new javax.swing.JMenuItem();
        itemBuscarPorYCliente = new javax.swing.JMenuItem();
        MenuCuenta = new javax.swing.JMenu();
        itemAgregarCuenta = new javax.swing.JMenuItem();
        itemBuscarCuenta = new javax.swing.JMenuItem();
        itemEliminarCuenta = new javax.swing.JMenuItem();
        itemEditarCuenta = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        subMenuReportesCuenta = new javax.swing.JMenu();
        itemBuscarPorXCuenta = new javax.swing.JMenuItem();
        itemBuscarPorYCuenta = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("_-.: BANCO MV :.-_");
        setName(".:: Banco MV ::."); // NOI18N

        MenuBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/bank_4011335.png"))); // NOI18N
        MenuBanco.setText("Banco");
        MenuBanco.setBorderPainted(false);
        MenuBanco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemAgregarBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemAgregarBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/medical-report_8506475.png"))); // NOI18N
        itemAgregarBanco.setText("Agregar Banco...");
        itemAgregarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarBancoActionPerformed(evt);
            }
        });
        MenuBanco.add(itemAgregarBanco);

        itemBuscarBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemBuscarBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/search_5953174.png"))); // NOI18N
        itemBuscarBanco.setText("Buscar Banco...");
        itemBuscarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarBancoActionPerformed(evt);
            }
        });
        MenuBanco.add(itemBuscarBanco);

        itemEliminarBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemEliminarBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/delete_5953164.png"))); // NOI18N
        itemEliminarBanco.setText("Eliminar Banco...");
        itemEliminarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarBancoActionPerformed(evt);
            }
        });
        MenuBanco.add(itemEliminarBanco);

        itemEditarBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemEditarBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/edit_5953114.png"))); // NOI18N
        itemEditarBanco.setText("Editar Banco...");
        itemEditarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarBancoActionPerformed(evt);
            }
        });
        MenuBanco.add(itemEditarBanco);
        MenuBanco.add(jSeparator1);

        subMenuReportesBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/informe.png"))); // NOI18N
        subMenuReportesBanco.setText("Reportes");

        itemBuscarPorXBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemBuscarPorXBanco.setText("Buscar por X");
        itemBuscarPorXBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarPorXBancoActionPerformed(evt);
            }
        });
        subMenuReportesBanco.add(itemBuscarPorXBanco);

        itemBuscarPorYBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemBuscarPorYBanco.setText("Buscar por Y");
        subMenuReportesBanco.add(itemBuscarPorYBanco);

        MenuBanco.add(subMenuReportesBanco);

        jMenuBar1.add(MenuBanco);

        MenuSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/banking_2239000.png"))); // NOI18N
        MenuSucursal.setText("Sucursal");
        MenuSucursal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemAgregarSucursal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemAgregarSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/medical-report_8506475.png"))); // NOI18N
        itemAgregarSucursal.setText("Agregar Sucursal...");
        itemAgregarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarSucursalActionPerformed(evt);
            }
        });
        MenuSucursal.add(itemAgregarSucursal);

        itemBuscarSucursal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemBuscarSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/search_5953174.png"))); // NOI18N
        itemBuscarSucursal.setText("Buscar Sucursal...");
        itemBuscarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarSucursalActionPerformed(evt);
            }
        });
        MenuSucursal.add(itemBuscarSucursal);

        itemEliminarSucursal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemEliminarSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/edit_5953114.png"))); // NOI18N
        itemEliminarSucursal.setText("Eliminar Sucursal...");
        itemEliminarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarSucursalActionPerformed(evt);
            }
        });
        MenuSucursal.add(itemEliminarSucursal);

        itemEditarSucursal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemEditarSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/delete_5953164.png"))); // NOI18N
        itemEditarSucursal.setText("Editar Sucursal...");
        itemEditarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarSucursalActionPerformed(evt);
            }
        });
        MenuSucursal.add(itemEditarSucursal);
        MenuSucursal.add(jSeparator2);

        MenuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/businessman_1597295.png"))); // NOI18N
        MenuEmpleado.setText("Empleado");

        itemAgregarEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemAgregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/medical-report_8506475.png"))); // NOI18N
        itemAgregarEmpleado.setText("Agregar Empleado...");
        itemAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarEmpleadoActionPerformed(evt);
            }
        });
        MenuEmpleado.add(itemAgregarEmpleado);

        itemBuscarEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemBuscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/search_5953174.png"))); // NOI18N
        itemBuscarEmpleado.setText("Buscar Empleado...");
        itemBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarEmpleadoActionPerformed(evt);
            }
        });
        MenuEmpleado.add(itemBuscarEmpleado);

        itemEliminarEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemEliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/delete_5953164.png"))); // NOI18N
        itemEliminarEmpleado.setText("Editar Empleado...");
        itemEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarEmpleadoActionPerformed(evt);
            }
        });
        MenuEmpleado.add(itemEliminarEmpleado);

        itemEditarEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemEditarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/edit_5953114.png"))); // NOI18N
        itemEditarEmpleado.setText("Editar Empleado...");
        itemEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarEmpleadoActionPerformed(evt);
            }
        });
        MenuEmpleado.add(itemEditarEmpleado);
        MenuEmpleado.add(jSeparator8);

        subMenuReportesEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/informe.png"))); // NOI18N
        subMenuReportesEmpleado.setText("Reportes");

        itemBuscarPorXEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemBuscarPorXEmpleado.setText("Buscar por x");
        subMenuReportesEmpleado.add(itemBuscarPorXEmpleado);

        itemBuscarPorYEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemBuscarPorYEmpleado.setText("Buscar por y");
        itemBuscarPorYEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarPorYEmpleadoActionPerformed(evt);
            }
        });
        subMenuReportesEmpleado.add(itemBuscarPorYEmpleado);

        MenuEmpleado.add(subMenuReportesEmpleado);

        MenuSucursal.add(MenuEmpleado);
        MenuSucursal.add(jSeparator6);

        subMenuReportesSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/informe.png"))); // NOI18N
        subMenuReportesSucursal.setText("Reportes");

        itemBuscarPorXSucursal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemBuscarPorXSucursal.setText("Buscar por x");
        subMenuReportesSucursal.add(itemBuscarPorXSucursal);

        itemBuscarPorYSucursal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemBuscarPorYSucursal.setText("Buscar por y");
        itemBuscarPorYSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarPorYSucursalActionPerformed(evt);
            }
        });
        subMenuReportesSucursal.add(itemBuscarPorYSucursal);

        MenuSucursal.add(subMenuReportesSucursal);

        jMenuBar1.add(MenuSucursal);

        MenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/male_1814271.png"))); // NOI18N
        MenuCliente.setText("Cliente");
        MenuCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemAgregarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/medical-report_8506475.png"))); // NOI18N
        itemAgregarCliente.setText("Agregar Cliente...");
        itemAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarClienteActionPerformed(evt);
            }
        });
        MenuCliente.add(itemAgregarCliente);

        itemBuscarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/search_5953174.png"))); // NOI18N
        itemBuscarCliente.setText("Buscar Cliente...");
        itemBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarClienteActionPerformed(evt);
            }
        });
        MenuCliente.add(itemBuscarCliente);

        itemEliminarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/delete_5953164.png"))); // NOI18N
        itemEliminarCliente.setText("Eliminar Cliente...");
        itemEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarClienteActionPerformed(evt);
            }
        });
        MenuCliente.add(itemEliminarCliente);

        itemEditarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/edit_5953114.png"))); // NOI18N
        itemEditarCliente.setText("Editar Cliente...");
        itemEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarClienteActionPerformed(evt);
            }
        });
        MenuCliente.add(itemEditarCliente);

        itemLoginUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemLoginUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/perfil-del-usuario.png"))); // NOI18N
        itemLoginUsuario.setText("Iniciar Sesion");
        itemLoginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginUsuarioActionPerformed(evt);
            }
        });
        MenuCliente.add(itemLoginUsuario);

        itemRecordarClaveUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemRecordarClaveUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/contrasenas.png"))); // NOI18N
        itemRecordarClaveUsuario.setText("Recordar Clave");
        MenuCliente.add(itemRecordarClaveUsuario);

        itemCambiarClaveUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemCambiarClaveUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/cambiar-la-contrasena.png"))); // NOI18N
        itemCambiarClaveUsuario.setText("Cambiar Clave");
        MenuCliente.add(itemCambiarClaveUsuario);

        itemSalirUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemSalirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/cerrar-sesion.png"))); // NOI18N
        itemSalirUsuario.setText("Salir");
        itemSalirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirUsuarioActionPerformed(evt);
            }
        });
        MenuCliente.add(itemSalirUsuario);
        MenuCliente.add(jSeparator9);

        subMenuReportesCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/informe.png"))); // NOI18N
        subMenuReportesCliente.setText("Reporte");

        itemBuscarPorXCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemBuscarPorXCliente.setText("Buscar por X");
        subMenuReportesCliente.add(itemBuscarPorXCliente);

        itemBuscarPorYCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemBuscarPorYCliente.setText("Buscar por y");
        subMenuReportesCliente.add(itemBuscarPorYCliente);

        MenuCliente.add(subMenuReportesCliente);

        jMenuBar1.add(MenuCliente);

        MenuCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/check_1094881.png"))); // NOI18N
        MenuCuenta.setText("Cuenta");
        MenuCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemAgregarCuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemAgregarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/medical-report_8506475.png"))); // NOI18N
        itemAgregarCuenta.setText("Agregar Cuenta...");
        itemAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarCuentaActionPerformed(evt);
            }
        });
        MenuCuenta.add(itemAgregarCuenta);

        itemBuscarCuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemBuscarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/search_5953174.png"))); // NOI18N
        itemBuscarCuenta.setText("Buscar Cuenta...");
        itemBuscarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarCuentaActionPerformed(evt);
            }
        });
        MenuCuenta.add(itemBuscarCuenta);

        itemEliminarCuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemEliminarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/delete_5953164.png"))); // NOI18N
        itemEliminarCuenta.setText("Eliminar Cuenta...");
        itemEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarCuentaActionPerformed(evt);
            }
        });
        MenuCuenta.add(itemEliminarCuenta);

        itemEditarCuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemEditarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/edit_5953114.png"))); // NOI18N
        itemEditarCuenta.setText("Editar Cuenta...");
        itemEditarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarCuentaActionPerformed(evt);
            }
        });
        MenuCuenta.add(itemEditarCuenta);
        MenuCuenta.add(jSeparator5);

        subMenuReportesCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/edwinmendoza/vistas/gui/iconos/informe.png"))); // NOI18N
        subMenuReportesCuenta.setText("Reporte");

        itemBuscarPorXCuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemBuscarPorXCuenta.setText("Buscar por x");
        subMenuReportesCuenta.add(itemBuscarPorXCuenta);

        itemBuscarPorYCuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemBuscarPorYCuenta.setText("Buscar por y");
        subMenuReportesCuenta.add(itemBuscarPorYCuenta);

        MenuCuenta.add(subMenuReportesCuenta);

        jMenuBar1.add(MenuCuenta);

        MenuAyuda.setText("Ayuda");
        MenuAyuda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setText("Acerca de");
        MenuAyuda.add(jMenuItem1);

        jMenuBar1.add(MenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("-.-.:: Banco MV ::.-.-");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemEliminarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarSucursalActionPerformed
        // TODO add your handling code here:
        VentanaCrudSucursal ventana = new VentanaCrudSucursal(this, true);
        ventana.setTitle("Eliminar Sucursal");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar(),
                                            ventana.getBotonAgregarEmpleado(),
                                            ventana.getRemoverEmpleado()
        };
        desabilitarBotones(miBotones);
        
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre(),
                                                            ventana.getCampoDireccion(),
                                                            ventana.getCampoCodigoPostal(),
                                                            ventana.getCampoInforme()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarSucursalActionPerformed

    private void itemBuscarPorXBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarPorXBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarPorXBancoActionPerformed

    private void itemAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarClienteActionPerformed
        // TODO add your handling code here:
        VentanaCrudCliente ventana = new VentanaCrudCliente(this, true);
        ventana.setTitle("Agregar Cliente");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarClienteActionPerformed

    private void itemAgregarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarSucursalActionPerformed
        // TODO add your handling code here:
        VentanaCrudSucursal ventana = new VentanaCrudSucursal(this, true);
        ventana.setTitle("Agregar Sucursal");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarSucursalActionPerformed

    private void itemBuscarPorYSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarPorYSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarPorYSucursalActionPerformed

    private void itemBuscarPorYEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarPorYEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemBuscarPorYEmpleadoActionPerformed

    private void itemAgregarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarBancoActionPerformed
        // TODO add your handling code here:
        VentanaCrudBanco ventanaBanco = new VentanaCrudBanco(this, true);
        ventanaBanco.setTitle("Agregar Banco");
        JButton miBotones[] = new JButton[]{
                                            ventanaBanco.getBotonBuscar()
                                            ,ventanaBanco.getBotonEditar()
                                            ,ventanaBanco.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventanaBanco.setLocationRelativeTo(this);
        ventanaBanco.setVisible(true);
    }//GEN-LAST:event_itemAgregarBancoActionPerformed

    private void itemAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarCuentaActionPerformed
      
        try {
            VentanaCrudCuenta ventana = new VentanaCrudCuenta(this, true);
            ventana.setTitle("Agregar Cuenta");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_itemAgregarCuentaActionPerformed

    private void itemAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarEmpleadoActionPerformed
        // TODO add your handling code here:
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);
        ventana.setTitle("Agregar Empleado");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonBuscar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemAgregarEmpleadoActionPerformed

    private void itemLoginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginUsuarioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login nuevo = new Login();
        nuevo.setLocationRelativeTo(this);
        nuevo.setVisible(true);
        
    }//GEN-LAST:event_itemLoginUsuarioActionPerformed

    private void itemSalirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirUsuarioActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_itemSalirUsuarioActionPerformed

    private void itemBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarClienteActionPerformed
        // TODO add your handling code here:
        VentanaCrudCliente ventana = new VentanaCrudCliente(this, true);
        ventana.setTitle("Buscar Cliente");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_itemBuscarClienteActionPerformed

    private void itemEditarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarBancoActionPerformed
        // TODO add your handling code here:
        VentanaCrudBanco ventanaBanco = new VentanaCrudBanco(this, true);
        ventanaBanco.setTitle("Editar Banco");
        JButton miBotones[] = new JButton[]{
                                            ventanaBanco.getBotonAgregar()
                                            ,ventanaBanco.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventanaBanco.getCampoNombre(),
                                                            
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventanaBanco.setLocationByPlatform(true);
        ventanaBanco.setVisible(true);
    }//GEN-LAST:event_itemEditarBancoActionPerformed

    private void itemBuscarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarBancoActionPerformed
        // TODO add your handling code here:
        VentanaCrudBanco ventanaBanco = new VentanaCrudBanco(this, true);
   
        ventanaBanco.setTitle("Buscar Banco");
        JButton miBotones[] = new JButton[]{
                                            ventanaBanco.getBotonAgregar()
                                            ,ventanaBanco.getBotonEditar()
                                            ,ventanaBanco.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventanaBanco.getCampoNombre(),
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventanaBanco.setLocationByPlatform(true);
        ventanaBanco.setVisible(true);
    }//GEN-LAST:event_itemBuscarBancoActionPerformed

    private void itemEliminarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarBancoActionPerformed
        // TODO add your handling code here:
        VentanaCrudBanco ventanaBanco = new VentanaCrudBanco(this, true);
        ventanaBanco.setTitle("Eliminar Banco");
        JButton miBotones[] = new JButton[]{
                                            ventanaBanco.getBotonAgregar()
                                            ,ventanaBanco.getBotonEditar()
        };
        desabilitarBotones(miBotones);
        
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventanaBanco.getCampoNombre(),

                                                            };
        campoDeSoLoLectura(campoDeText);
        ventanaBanco.setLocationByPlatform(true);
        ventanaBanco.setVisible(true);
    }//GEN-LAST:event_itemEliminarBancoActionPerformed

    private void itemBuscarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarSucursalActionPerformed
        // TODO add your handling code here:
        VentanaCrudSucursal ventana = new VentanaCrudSucursal(this, true);
   
        ventana.setTitle("Buscar Sucursal");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
                                            ,ventana.getBotonAgregarEmpleado(),
                                            ventana.getRemoverEmpleado()
        };
        desabilitarBotones(miBotones);
        
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre(),
                                                            ventana.getCampoDireccion(),
                                                            ventana.getCampoCodigoPostal(),
                                                            ventana.getCampoInforme()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarSucursalActionPerformed

    private void itemEditarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarSucursalActionPerformed
        // TODO add your handling code here:
        VentanaCrudSucursal ventana = new VentanaCrudSucursal(this, true);
        ventana.setTitle("Editar Sucursal");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEliminar(),
                                            ventana.getBotonAgregarEmpleado(),
                                            ventana.getRemoverEmpleado()
        };
        desabilitarBotones(miBotones);
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre(),
                                                            ventana.getCampoDireccion(),
                                                            ventana.getCampoCodigoPostal(),
                                                            ventana.getCampoInforme()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarSucursalActionPerformed

    private void itemBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarEmpleadoActionPerformed
        // TODO add your handling code here:
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);
   
        ventana.setTitle("Buscar Empleado");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre(),
                                                            ventana.getCampoCargo(),
                                                            ventana.getCampoClave(),
                                                            ventana.getCampoDireccion(),
                                                            ventana.getCampoCiudad()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarEmpleadoActionPerformed

    private void itemEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);
        ventana.setTitle("Eliminar Empleado");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
        };
        desabilitarBotones(miBotones);
        
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre(),
                                                            ventana.getCampoCargo(),
                                                            ventana.getCampoClave(),
                                                            ventana.getCampoDireccion(),
                                                            ventana.getCampoCiudad()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarEmpleadoActionPerformed

    private void itemEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarEmpleadoActionPerformed
        // TODO add your handling code here:
        VentanaCrudEmpleado ventana = new VentanaCrudEmpleado(this, true);
        ventana.setTitle("Editar Empleado");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoNombre(),
                                                            ventana.getCampoCargo(),
                                                            ventana.getCampoClave(),
                                                            ventana.getCampoDireccion(),
                                                            ventana.getCampoCiudad()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarEmpleadoActionPerformed

    private void itemBuscarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarCuentaActionPerformed
        // TODO add your handling code here:
        VentanaCrudCuenta ventana = null;
        try {
            ventana = new VentanaCrudCuenta(this, true);
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
   
        ventana.setTitle("Buscar Cuenta");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoSaldoActual()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemBuscarCuentaActionPerformed

    private void itemEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarCuentaActionPerformed
        // TODO add your handling code here:
        VentanaCrudCuenta ventana = null;
        try {
            ventana = new VentanaCrudCuenta(this, true);
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventana.setTitle("Eliminar Cuenta");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
        };
        desabilitarBotones(miBotones);
        
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoSaldoActual()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarCuentaActionPerformed

    private void itemEditarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarCuentaActionPerformed
        // TODO add your handling code here:
        VentanaCrudCuenta ventana =  null;
        try {
            ventana = new VentanaCrudCuenta(this, true);
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventana.setTitle("Editar Cuenta");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        JTextComponent campoDeText[] = new JTextComponent[]{
                                                            ventana.getCampoSaldoActual()
                                                            };
        campoDeSoLoLectura(campoDeText);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarCuentaActionPerformed

    private void itemEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarClienteActionPerformed
        // TODO add your handling code here:
        VentanaCrudCliente ventana = new VentanaCrudCliente(this, true);
        ventana.setTitle("Eliminar Cliente");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEditar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEliminarClienteActionPerformed

    private void itemEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarClienteActionPerformed
        // TODO add your handling code here:
        VentanaCrudCliente ventana = new VentanaCrudCliente(this, true);
        ventana.setTitle("Editar Cliente");
        JButton miBotones[] = new JButton[]{
                                            ventana.getBotonAgregar()
                                            ,ventana.getBotonEliminar()
        };
        desabilitarBotones(miBotones);
        ventana.setLocationByPlatform(true);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemEditarClienteActionPerformed

    public void desabilitarBotones(JButton botones[]){
        for(JButton boton: botones){
            boton.setEnabled(false);
        }
    }
    
    public void campoDeSoLoLectura(JTextComponent campoTexto[]){
        for (JTextComponent component : campoTexto) {
            component.setEditable(false);
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenu MenuBanco;
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JMenu MenuCuenta;
    private javax.swing.JMenu MenuEmpleado;
    private javax.swing.JMenu MenuSucursal;
    private javax.swing.JMenuItem itemAgregarBanco;
    private javax.swing.JMenuItem itemAgregarCliente;
    private javax.swing.JMenuItem itemAgregarCuenta;
    private javax.swing.JMenuItem itemAgregarEmpleado;
    private javax.swing.JMenuItem itemAgregarSucursal;
    private javax.swing.JMenuItem itemBuscarBanco;
    private javax.swing.JMenuItem itemBuscarCliente;
    private javax.swing.JMenuItem itemBuscarCuenta;
    private javax.swing.JMenuItem itemBuscarEmpleado;
    private javax.swing.JMenuItem itemBuscarPorXBanco;
    private javax.swing.JMenuItem itemBuscarPorXCliente;
    private javax.swing.JMenuItem itemBuscarPorXCuenta;
    private javax.swing.JMenuItem itemBuscarPorXEmpleado;
    private javax.swing.JMenuItem itemBuscarPorXSucursal;
    private javax.swing.JMenuItem itemBuscarPorYBanco;
    private javax.swing.JMenuItem itemBuscarPorYCliente;
    private javax.swing.JMenuItem itemBuscarPorYCuenta;
    private javax.swing.JMenuItem itemBuscarPorYEmpleado;
    private javax.swing.JMenuItem itemBuscarPorYSucursal;
    private javax.swing.JMenuItem itemBuscarSucursal;
    private javax.swing.JMenuItem itemCambiarClaveUsuario;
    private javax.swing.JMenuItem itemEditarBanco;
    private javax.swing.JMenuItem itemEditarCliente;
    private javax.swing.JMenuItem itemEditarCuenta;
    private javax.swing.JMenuItem itemEditarEmpleado;
    private javax.swing.JMenuItem itemEditarSucursal;
    private javax.swing.JMenuItem itemEliminarBanco;
    private javax.swing.JMenuItem itemEliminarCliente;
    private javax.swing.JMenuItem itemEliminarCuenta;
    private javax.swing.JMenuItem itemEliminarEmpleado;
    private javax.swing.JMenuItem itemEliminarSucursal;
    private javax.swing.JMenuItem itemLoginUsuario;
    private javax.swing.JMenuItem itemRecordarClaveUsuario;
    private javax.swing.JMenuItem itemSalirUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu subMenuReportesBanco;
    private javax.swing.JMenu subMenuReportesCliente;
    private javax.swing.JMenu subMenuReportesCuenta;
    private javax.swing.JMenu subMenuReportesEmpleado;
    private javax.swing.JMenu subMenuReportesSucursal;
    // End of variables declaration//GEN-END:variables



}
